
/*
 * This file was generated by the SOM Compiler.
 * FileName: idl\wpstack.h.
 * Generated using:
 *     SOM Precompiler somipc: 2.29.1.17
 *     SOM Emitter emith: 2.47
 */

#ifndef SOM_Stack_h
#define SOM_Stack_h


/*
 * Passthru lines: File: "C.h", "before"
 */
#define STK_AWAKECOUNT      1
#define STK_PERSISTENTCOUNT 2


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef Stack
#define Stack SOMObject
#endif
#include <wpabs.h>

/*
 * Start of bindings for IDL types
 */

#ifndef SOMClass
    #define SOMClass SOMObject
#endif /* SOMClass */
#ifndef WPFolder
    #define WPFolder SOMObject
#endif /* WPFolder */
#ifndef M_WPObject
    #define M_WPObject SOMObject
#endif /* M_WPObject */
#ifndef WPObject
    #define WPObject SOMObject
#endif /* WPObject */
#ifndef WPImageFile
    #define WPImageFile SOMObject
#endif /* WPImageFile */
#ifndef M_WPAbstract
    #define M_WPAbstract SOMObject
#endif /* M_WPAbstract */
#ifndef M_Stack
    #define M_Stack SOMObject
#endif /* M_Stack */

/*
 * End of bindings for IDL types.
 */

#define Stack_MajorVersion 1
#define Stack_MinorVersion 2

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define StackNewClass c
#pragma linkage(c, system)
#define StackClassData d
#define StackCClassData x
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define Stack_classObj StackClassData.classObject
#define _Stack Stack_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK StackNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(StackNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct StackClassDataStructure {
	SOMClass *classObject;
	somMToken InsertStackPage;
	somMToken Lock;
	somMToken Pop;
	somMToken Push;
	somMToken Unlock;
} SOMDLINK StackClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct StackCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK StackCClassData;

/*
 * New and Renew macros for Stack
 */
#define StackNew() \
   ( _Stack ? \
	_somNew(_Stack) \
	: ( StackNewClass(\
		Stack_MajorVersion, \
		Stack_MinorVersion),\
	   _somNew(_Stack)))
#define StackRenew(buf) \
   ( _Stack ? \
	_somRenew(_Stack, buf) \
	: ( StackNewClass(\
		Stack_MajorVersion, \
		Stack_MinorVersion),\
	   _somRenew(_Stack, buf)))

/*
 * Override method: wpAddSettingsPages
 */
#define Stack_wpAddSettingsPages(somSelf,hwndNotebook) \
	WPObject_wpAddSettingsPages(somSelf,hwndNotebook)

/*
 * Override method: wpFree
 */
#define Stack_wpFree(somSelf) \
	WPObject_wpFree(somSelf)

/*
 * Override method: wpInitData
 */
#define Stack_wpInitData(somSelf) \
	WPObject_wpInitData(somSelf)

/*
 * Override method: wpObjectReady
 */
#define Stack_wpObjectReady(somSelf,ulCode,refObject) \
	WPObject_wpObjectReady(somSelf,ulCode,refObject)

/*
 * Override method: wpRestoreState
 */
#define Stack_wpRestoreState(somSelf,ulReserved) \
	WPObject_wpRestoreState(somSelf,ulReserved)

/*
 * Override method: wpSaveState
 */
#define Stack_wpSaveState(somSelf) \
	WPObject_wpSaveState(somSelf)

/*
 * Override method: wpSetup
 */
#define Stack_wpSetup(somSelf,pszSetupString) \
	WPObject_wpSetup(somSelf,pszSetupString)

/*
 * Override method: wpSetupOnce
 */
#define Stack_wpSetupOnce(somSelf,pszSetupString) \
	WPObject_wpSetupOnce(somSelf,pszSetupString)

/*
 * Override method: wpUnInitData
 */
#define Stack_wpUnInitData(somSelf) \
	WPObject_wpUnInitData(somSelf)

/*
 * New Method: InsertStackPage
 */
typedef ULONG   SOMLINK somTP_Stack_InsertStackPage(Stack *somSelf, 
		HWND hwndDlg);
#pragma linkage(somTP_Stack_InsertStackPage, system)
typedef somTP_Stack_InsertStackPage *somTD_Stack_InsertStackPage;
#define somMD_Stack_InsertStackPage "::Stack::InsertStackPage"
#define Stack_InsertStackPage(somSelf,hwndDlg) \
    (SOM_Resolve(somSelf, Stack, InsertStackPage) \
	(somSelf,hwndDlg))
#ifndef SOMGD_InsertStackPage
    #if (defined(_InsertStackPage) || defined(__InsertStackPage))
        #undef _InsertStackPage
        #undef __InsertStackPage
        #define SOMGD_InsertStackPage 1
    #else
        #define _InsertStackPage Stack_InsertStackPage
    #endif /* _InsertStackPage */
#endif /* SOMGD_InsertStackPage */

/*
 * New Method: Lock
 */
typedef BOOL   SOMLINK somTP_Stack_Lock(Stack *somSelf);
#pragma linkage(somTP_Stack_Lock, system)
typedef somTP_Stack_Lock *somTD_Stack_Lock;
#define somMD_Stack_Lock "::Stack::Lock"
#define Stack_Lock(somSelf) \
    (SOM_Resolve(somSelf, Stack, Lock) \
	(somSelf))
#ifndef SOMGD_Lock
    #if (defined(_Lock) || defined(__Lock))
        #undef _Lock
        #undef __Lock
        #define SOMGD_Lock 1
    #else
        #define _Lock Stack_Lock
    #endif /* _Lock */
#endif /* SOMGD_Lock */

/*
 * New Method: Pop
 */
typedef BOOL   SOMLINK somTP_Stack_Pop(Stack *somSelf, 
		PVOID pBuffer, 
		ULONG* pcbBuffer);
#pragma linkage(somTP_Stack_Pop, system)
typedef somTP_Stack_Pop *somTD_Stack_Pop;
#define somMD_Stack_Pop "::Stack::Pop"
#define Stack_Pop(somSelf,pBuffer,pcbBuffer) \
    (SOM_Resolve(somSelf, Stack, Pop) \
	(somSelf,pBuffer,pcbBuffer))
#ifndef SOMGD_Pop
    #if (defined(_Pop) || defined(__Pop))
        #undef _Pop
        #undef __Pop
        #define SOMGD_Pop 1
    #else
        #define _Pop Stack_Pop
    #endif /* _Pop */
#endif /* SOMGD_Pop */

/*
 * New Method: Push
 */
typedef BOOL   SOMLINK somTP_Stack_Push(Stack *somSelf, 
		PVOID pNewItem, 
		ULONG cbNewItem);
#pragma linkage(somTP_Stack_Push, system)
typedef somTP_Stack_Push *somTD_Stack_Push;
#define somMD_Stack_Push "::Stack::Push"
#define Stack_Push(somSelf,pNewItem,cbNewItem) \
    (SOM_Resolve(somSelf, Stack, Push) \
	(somSelf,pNewItem,cbNewItem))
#ifndef SOMGD_Push
    #if (defined(_Push) || defined(__Push))
        #undef _Push
        #undef __Push
        #define SOMGD_Push 1
    #else
        #define _Push Stack_Push
    #endif /* _Push */
#endif /* SOMGD_Push */

/*
 * New Method: Unlock
 */
typedef BOOL   SOMLINK somTP_Stack_Unlock(Stack *somSelf);
#pragma linkage(somTP_Stack_Unlock, system)
typedef somTP_Stack_Unlock *somTD_Stack_Unlock;
#define somMD_Stack_Unlock "::Stack::Unlock"
#define Stack_Unlock(somSelf) \
    (SOM_Resolve(somSelf, Stack, Unlock) \
	(somSelf))
#ifndef SOMGD_Unlock
    #if (defined(_Unlock) || defined(__Unlock))
        #undef _Unlock
        #undef __Unlock
        #define SOMGD_Unlock 1
    #else
        #define _Unlock Stack_Unlock
    #endif /* _Unlock */
#endif /* SOMGD_Unlock */
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define Stack_wpQueryHandle WPObject_wpQueryHandle
#define Stack_wpSaveImmediate WPObject_wpSaveImmediate
#define Stack_wpSetTitle WPObject_wpSetTitle
#define Stack_wpCopyObject WPObject_wpCopyObject
#define Stack_wpMoveObject WPObject_wpMoveObject
#define Stack_wpQueryIcon WPObject_wpQueryIcon
#define Stack_wpQueryIconData WPObject_wpQueryIconData
#define Stack_wpSetIconData WPObject_wpSetIconData
#define Stack_wpDragOver WPObject_wpDragOver
#define Stack_wpReplaceObject WPObject_wpReplaceObject
#define Stack_wpQueryNameClashOptions WPObject_wpQueryNameClashOptions
#define Stack_somDefaultInit SOMObject_somDefaultInit
#define Stack_somDestruct SOMObject_somDestruct
#define Stack_wpIdentify WPObject_wpIdentify
#define Stack_wpAddObjectGeneralPage WPObject_wpAddObjectGeneralPage
#define Stack_wpAddObjectGeneralPage2 WPObject_wpAddObjectGeneralPage2
#define Stack_wpAddObjectWindowPage WPObject_wpAddObjectWindowPage
#define Stack_wpAddToObjUseList WPObject_wpAddToObjUseList
#define Stack_wpAllocMem WPObject_wpAllocMem
#define Stack_wpAppendObject WPObject_wpAppendObject
#define Stack_wpAssertObjectMutexSem WPObject_wpAssertObjectMutexSem
#define Stack_wpClose WPObject_wpClose
#define Stack_wpCnrInsertObject WPObject_wpCnrInsertObject
#define Stack_wpCnrRemoveObject WPObject_wpCnrRemoveObject
#define Stack_wpCnrSetEmphasis WPObject_wpCnrSetEmphasis
#define Stack_wpConfirmDelete WPObject_wpConfirmDelete
#define Stack_wpConfirmObjectTitle WPObject_wpConfirmObjectTitle
#define Stack_wpCopiedFromTemplate WPObject_wpCopiedFromTemplate
#define Stack_wpCreateAnother WPObject_wpCreateAnother
#define Stack_wpCreateFromTemplate WPObject_wpCreateFromTemplate
#define Stack_wpCreateShadowObject WPObject_wpCreateShadowObject
#define Stack_wpDelete WPObject_wpDelete
#define Stack_wpDeleteFromObjUseList WPObject_wpDeleteFromObjUseList
#define Stack_wpDisplayHelp WPObject_wpDisplayHelp
#define Stack_wpDisplayMenu WPObject_wpDisplayMenu
#define Stack_wpDoesObjectMatch WPObject_wpDoesObjectMatch
#define Stack_wpDraggedOverObject WPObject_wpDraggedOverObject
#define Stack_wpDrop WPObject_wpDrop
#define Stack_wpDroppedOnObject WPObject_wpDroppedOnObject
#define Stack_wpEndConversation WPObject_wpEndConversation
#define Stack_wpFilterPopupMenu WPObject_wpFilterPopupMenu
#define Stack_wpFilterMenu WPObject_wpFilterMenu
#define Stack_wpFindUseItem WPObject_wpFindUseItem
#define Stack_wpFormatDragItem WPObject_wpFormatDragItem
#define Stack_wpFreeMem WPObject_wpFreeMem
#define Stack_wpHide WPObject_wpHide
#define Stack_wpInsertPopupMenuItems WPObject_wpInsertPopupMenuItems
#define Stack_wpInsertMenuItems WPObject_wpInsertMenuItems
#define Stack_wpInsertSettingsPage WPObject_wpInsertSettingsPage
#define Stack_wpMenuItemHelpSelected WPObject_wpMenuItemHelpSelected
#define Stack_wpMenuItemSelected WPObject_wpMenuItemSelected
#define Stack_wpModifyPopupMenu WPObject_wpModifyPopupMenu
#define Stack_wpModifyMenu WPObject_wpModifyMenu
#define Stack_wpOpen WPObject_wpOpen
#define Stack_wpPrintObject WPObject_wpPrintObject
#define Stack_wpQueryConcurrentView WPObject_wpQueryConcurrentView
#define Stack_wpQueryButtonAppearance WPObject_wpQueryButtonAppearance
#define Stack_wpQueryConfirmations WPObject_wpQueryConfirmations
#define Stack_wpQueryDefaultHelp WPObject_wpQueryDefaultHelp
#define Stack_wpQueryDefaultView WPObject_wpQueryDefaultView
#define Stack_wpQueryDetailsData WPObject_wpQueryDetailsData
#define Stack_wpQueryError WPObject_wpQueryError
#define Stack_wpSetFolder WPObject_wpSetFolder
#define Stack_wpQueryFolder WPObject_wpQueryFolder
#define Stack_wpQueryMinWindow WPObject_wpQueryMinWindow
#define Stack_wpQueryStyle WPObject_wpQueryStyle
#define Stack_wpSetTaskRec WPObject_wpSetTaskRec
#define Stack_wpFindTaskRec WPObject_wpFindTaskRec
#define Stack_wpQueryTitle WPObject_wpQueryTitle
#define Stack_wpRegisterView WPObject_wpRegisterView
#define Stack_wpReleaseObjectMutexSem WPObject_wpReleaseObjectMutexSem
#define Stack_wpRender WPObject_wpRender
#define Stack_wpRenderComplete WPObject_wpRenderComplete
#define Stack_wpRequestObjectMutexSem WPObject_wpRequestObjectMutexSem
#define Stack_wpRestore WPObject_wpRestore
#define Stack_wpRestoreData WPObject_wpRestoreData
#define Stack_wpRestoreLong WPObject_wpRestoreLong
#define Stack_wpRestoreString WPObject_wpRestoreString
#define Stack_wpSaveData WPObject_wpSaveData
#define Stack_wpSaveDeferred WPObject_wpSaveDeferred
#define Stack_wpSaveLong WPObject_wpSaveLong
#define Stack_wpSaveString WPObject_wpSaveString
#define Stack_wpScanSetupString WPObject_wpScanSetupString
#define Stack_wpSetConcurrentView WPObject_wpSetConcurrentView
#define Stack_wpSetButtonAppearance WPObject_wpSetButtonAppearance
#define Stack_wpSetDefaultHelp WPObject_wpSetDefaultHelp
#define Stack_wpSetDefaultView WPObject_wpSetDefaultView
#define Stack_wpSetError WPObject_wpSetError
#define Stack_wpQueryScreenGroupID WPObject_wpQueryScreenGroupID
#define Stack_wpSetIcon WPObject_wpSetIcon
#define Stack_wpSetMinWindow WPObject_wpSetMinWindow
#define Stack_wpModifyStyle WPObject_wpModifyStyle
#define Stack_wpSwitchTo WPObject_wpSwitchTo
#define Stack_wpViewObject WPObject_wpViewObject
#define Stack_wpQueryTrueStyle WPObject_wpQueryTrueStyle
#define Stack_wpUnlockObject WPObject_wpUnlockObject
#define Stack_wpIsObjectInitialized WPObject_wpIsObjectInitialized
#define Stack_wpCreateShadowObjectExt WPObject_wpCreateShadowObjectExt
#define Stack_wpCnrDeleteUseItem WPObject_wpCnrDeleteUseItem
#define Stack_wpIsDeleteable WPObject_wpIsDeleteable
#define Stack_wpQueryCoreRecord WPObject_wpQueryCoreRecord
#define Stack_wpSetObjectID WPObject_wpSetObjectID
#define Stack_wpQueryObjectID WPObject_wpQueryObjectID
#define Stack_wpSetDefaultIconPos WPObject_wpSetDefaultIconPos
#define Stack_wpQueryDefaultIconPos WPObject_wpQueryDefaultIconPos
#define Stack_wpCnrRefreshDetails WPObject_wpCnrRefreshDetails
#define Stack_wpFindViewItem WPObject_wpFindViewItem
#define Stack_wpLockObject WPObject_wpLockObject
#define Stack_wpIsLocked WPObject_wpIsLocked
#define Stack_wpQueryContainerFlagPtr WPObject_wpQueryContainerFlagPtr
#define Stack_wpWaitForClose WPObject_wpWaitForClose
#define Stack_wpSetMenuStyle WPObject_wpSetMenuStyle
#define Stack_wpQueryMenuStyle WPObject_wpQueryMenuStyle
#define Stack_wpSetStyle WPObject_wpSetStyle
#define Stack_somInit SOMObject_somInit
#define Stack_somUninit SOMObject_somUninit
#define Stack_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define Stack_somDefaultAssign SOMObject_somDefaultAssign
#define Stack_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define Stack_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define Stack_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define Stack_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define Stack_somDefaultVAssign SOMObject_somDefaultVAssign
#define Stack_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define Stack_somFree SOMObject_somFree
#define Stack_somGetClass SOMObject_somGetClass
#define Stack_somGetClassName SOMObject_somGetClassName
#define Stack_somGetSize SOMObject_somGetSize
#define Stack_somIsA SOMObject_somIsA
#define Stack_somIsInstanceOf SOMObject_somIsInstanceOf
#define Stack_somRespondsTo SOMObject_somRespondsTo
#define Stack_somDispatch SOMObject_somDispatch
#define Stack_somClassDispatch SOMObject_somClassDispatch
#define Stack_somCastObj SOMObject_somCastObj
#define Stack_somResetObj SOMObject_somResetObj
#define Stack_somDispatchV SOMObject_somDispatchV
#define Stack_somDispatchL SOMObject_somDispatchL
#define Stack_somDispatchA SOMObject_somDispatchA
#define Stack_somDispatchD SOMObject_somDispatchD
#define Stack_somPrintSelf SOMObject_somPrintSelf
#define Stack_somDumpSelf SOMObject_somDumpSelf
#define Stack_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_Stack_h */

#ifndef SOM_M_Stack_h
#define SOM_M_Stack_h


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef M_Stack
#define M_Stack SOMObject
#endif
#include <wpabs.h>

/*
 * Start of bindings for IDL types
 */


/*
 * End of bindings for IDL types.
 */

#define M_Stack_MajorVersion 1
#define M_Stack_MinorVersion 2

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define M_StackNewClass c
#pragma linkage(c, system)
#define M_StackClassData d
#define M_StackCClassData x
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define M_Stack_classObj M_StackClassData.classObject
#define _M_Stack M_Stack_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK M_StackNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(M_StackNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct M_StackClassDataStructure {
	SOMClass *classObject;
	somMToken clsDecObjectCount;
	somMToken clsIncObjectCount;
	somMToken clsQueryModuleHandle;
	somMToken clsQueryObjectCount;
} SOMDLINK M_StackClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct M_StackCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK M_StackCClassData;

/*
 * New and Renew macros for M_Stack
 */
#define M_StackNew() \
   ( _M_Stack ? \
	_somNew(_M_Stack) \
	: ( M_StackNewClass(\
		M_Stack_MajorVersion, \
		M_Stack_MinorVersion),\
	   _somNew(_M_Stack)))
#define M_StackRenew(buf) \
   ( _M_Stack ? \
	_somRenew(_M_Stack, buf) \
	: ( M_StackNewClass(\
		M_Stack_MajorVersion, \
		M_Stack_MinorVersion),\
	   _somRenew(_M_Stack, buf)))

/*
 * Override method: wpclsInitData
 */
#define M_Stack_wpclsInitData(somSelf) \
	M_WPObject_wpclsInitData(somSelf)

/*
 * Override method: wpclsQueryDefaultHelp
 */
#define M_Stack_wpclsQueryDefaultHelp(somSelf,pHelpPanelId,pszHelpLibrary) \
	M_WPObject_wpclsQueryDefaultHelp(somSelf,pHelpPanelId,pszHelpLibrary)

/*
 * Override method: wpclsQueryDefaultView
 */
#define M_Stack_wpclsQueryDefaultView(somSelf) \
	M_WPObject_wpclsQueryDefaultView(somSelf)

/*
 * Override method: wpclsQueryIconData
 */
#define M_Stack_wpclsQueryIconData(somSelf,pIconInfo) \
	M_WPObject_wpclsQueryIconData(somSelf,pIconInfo)

/*
 * New Method: clsDecObjectCount
 */
typedef ULONG   SOMLINK somTP_M_Stack_clsDecObjectCount(M_Stack *somSelf, 
		ULONG ulCountType);
#pragma linkage(somTP_M_Stack_clsDecObjectCount, system)
typedef somTP_M_Stack_clsDecObjectCount *somTD_M_Stack_clsDecObjectCount;
#define somMD_M_Stack_clsDecObjectCount "::M_Stack::clsDecObjectCount"
#define M_Stack_clsDecObjectCount(somSelf,ulCountType) \
    (SOM_Resolve(somSelf, M_Stack, clsDecObjectCount) \
	(somSelf,ulCountType))
#ifndef SOMGD_clsDecObjectCount
    #if (defined(_clsDecObjectCount) || defined(__clsDecObjectCount))
        #undef _clsDecObjectCount
        #undef __clsDecObjectCount
        #define SOMGD_clsDecObjectCount 1
    #else
        #define _clsDecObjectCount M_Stack_clsDecObjectCount
    #endif /* _clsDecObjectCount */
#endif /* SOMGD_clsDecObjectCount */

/*
 * New Method: clsIncObjectCount
 */
typedef ULONG   SOMLINK somTP_M_Stack_clsIncObjectCount(M_Stack *somSelf, 
		ULONG ulCountType);
#pragma linkage(somTP_M_Stack_clsIncObjectCount, system)
typedef somTP_M_Stack_clsIncObjectCount *somTD_M_Stack_clsIncObjectCount;
#define somMD_M_Stack_clsIncObjectCount "::M_Stack::clsIncObjectCount"
#define M_Stack_clsIncObjectCount(somSelf,ulCountType) \
    (SOM_Resolve(somSelf, M_Stack, clsIncObjectCount) \
	(somSelf,ulCountType))
#ifndef SOMGD_clsIncObjectCount
    #if (defined(_clsIncObjectCount) || defined(__clsIncObjectCount))
        #undef _clsIncObjectCount
        #undef __clsIncObjectCount
        #define SOMGD_clsIncObjectCount 1
    #else
        #define _clsIncObjectCount M_Stack_clsIncObjectCount
    #endif /* _clsIncObjectCount */
#endif /* SOMGD_clsIncObjectCount */

/*
 * New Method: clsQueryModuleHandle
 */
typedef HMODULE   SOMLINK somTP_M_Stack_clsQueryModuleHandle(M_Stack *somSelf);
#pragma linkage(somTP_M_Stack_clsQueryModuleHandle, system)
typedef somTP_M_Stack_clsQueryModuleHandle *somTD_M_Stack_clsQueryModuleHandle;
#define somMD_M_Stack_clsQueryModuleHandle "::M_Stack::clsQueryModuleHandle"
#define M_Stack_clsQueryModuleHandle(somSelf) \
    (SOM_Resolve(somSelf, M_Stack, clsQueryModuleHandle) \
	(somSelf))
#ifndef SOMGD_clsQueryModuleHandle
    #if (defined(_clsQueryModuleHandle) || defined(__clsQueryModuleHandle))
        #undef _clsQueryModuleHandle
        #undef __clsQueryModuleHandle
        #define SOMGD_clsQueryModuleHandle 1
    #else
        #define _clsQueryModuleHandle M_Stack_clsQueryModuleHandle
    #endif /* _clsQueryModuleHandle */
#endif /* SOMGD_clsQueryModuleHandle */

/*
 * New Method: clsQueryObjectCount
 */
typedef ULONG   SOMLINK somTP_M_Stack_clsQueryObjectCount(M_Stack *somSelf, 
		ULONG ulCountType);
#pragma linkage(somTP_M_Stack_clsQueryObjectCount, system)
typedef somTP_M_Stack_clsQueryObjectCount *somTD_M_Stack_clsQueryObjectCount;
#define somMD_M_Stack_clsQueryObjectCount "::M_Stack::clsQueryObjectCount"
#define M_Stack_clsQueryObjectCount(somSelf,ulCountType) \
    (SOM_Resolve(somSelf, M_Stack, clsQueryObjectCount) \
	(somSelf,ulCountType))
#ifndef SOMGD_clsQueryObjectCount
    #if (defined(_clsQueryObjectCount) || defined(__clsQueryObjectCount))
        #undef _clsQueryObjectCount
        #undef __clsQueryObjectCount
        #define SOMGD_clsQueryObjectCount 1
    #else
        #define _clsQueryObjectCount M_Stack_clsQueryObjectCount
    #endif /* _clsQueryObjectCount */
#endif /* SOMGD_clsQueryObjectCount */
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define M_Stack_wpclsQuerySetting M_WPAbstract_wpclsQuerySetting
#define M_Stack_wpclsSetSetting M_WPAbstract_wpclsSetSetting
#define M_Stack_wpclsQueryTitle M_WPObject_wpclsQueryTitle
#define M_Stack_wpclsObjectFromHandle M_WPObject_wpclsObjectFromHandle
#define M_Stack_wpclsCreateDefaultTemplates M_WPObject_wpclsCreateDefaultTemplates
#define M_Stack_wpclsMakeAwake M_WPObject_wpclsMakeAwake
#define M_Stack_wpclsNew M_WPObject_wpclsNew
#define M_Stack_wpclsQueryDetails M_WPObject_wpclsQueryDetails
#define M_Stack_wpclsQueryDetailsInfo M_WPObject_wpclsQueryDetailsInfo
#define M_Stack_wpclsQueryExtendedCriteria M_WPObject_wpclsQueryExtendedCriteria
#define M_Stack_wpclsQueryFolder M_WPObject_wpclsQueryFolder
#define M_Stack_wpclsQueryIcon M_WPObject_wpclsQueryIcon
#define M_Stack_wpclsQuerySearchInfo M_WPObject_wpclsQuerySearchInfo
#define M_Stack_wpclsQueryStyle M_WPObject_wpclsQueryStyle
#define M_Stack_wpclsUnInitData M_WPObject_wpclsUnInitData
#define M_Stack_wpclsFindObjectFirst M_WPObject_wpclsFindObjectFirst
#define M_Stack_wpclsFindObjectNext M_WPObject_wpclsFindObjectNext
#define M_Stack_wpclsFindObjectEnd M_WPObject_wpclsFindObjectEnd
#define M_Stack_wpclsSetError M_WPObject_wpclsSetError
#define M_Stack_wpclsQueryError M_WPObject_wpclsQueryError
#define M_Stack_wpclsQuerySettingsPageSize M_WPObject_wpclsQuerySettingsPageSize
#define M_Stack_wpclsQueryObject M_WPObject_wpclsQueryObject
#define M_Stack_wpclsQueryButtonAppearance M_WPObject_wpclsQueryButtonAppearance
#define M_Stack_wpclsDecUsage M_WPObject_wpclsDecUsage
#define M_Stack_wpclsIncUsage M_WPObject_wpclsIncUsage
#define M_Stack_wpclsInsertMultipleObjects M_WPObject_wpclsInsertMultipleObjects
#define M_Stack_wpclsFindOneObject M_WPObject_wpclsFindOneObject
#define M_Stack_wpclsSetSettingsPageSize M_WPObject_wpclsSetSettingsPageSize
#define M_Stack_wpclsSetIconData M_WPObject_wpclsSetIconData
#define M_Stack_wpclsSetIcon M_WPObject_wpclsSetIcon
#define M_Stack_wpclsRemoveObjects M_WPObject_wpclsRemoveObjects
#define M_Stack_somUninit SOMObject_somUninit
#define M_Stack_somClassReady SOMClass_somClassReady
#define M_Stack_somNew SOMClass_somNew
#define M_Stack_somRenew SOMClass_somRenew
#define M_Stack__get_somDataAlignment SOMClass__get_somDataAlignment
#define M_Stack__get_somInstanceDataOffsets SOMClass__get_somInstanceDataOffsets
#define M_Stack__get_somDirectInitClasses SOMClass__get_somDirectInitClasses
#define M_Stack_somNewNoInit SOMClass_somNewNoInit
#define M_Stack_somRenewNoInit SOMClass_somRenewNoInit
#define M_Stack_somRenewNoZero SOMClass_somRenewNoZero
#define M_Stack_somRenewNoInitNoZero SOMClass_somRenewNoInitNoZero
#define M_Stack_somAllocate SOMClass_somAllocate
#define M_Stack_somDeallocate SOMClass_somDeallocate
#define M_Stack_somInitClass SOMClass_somInitClass
#define M_Stack_somInitMIClass SOMClass_somInitMIClass
#define M_Stack_somAddStaticMethod SOMClass_somAddStaticMethod
#define M_Stack_somAddDynamicMethod SOMClass_somAddDynamicMethod
#define M_Stack_somOverrideSMethod SOMClass_somOverrideSMethod
#define M_Stack_somGetApplyStub SOMClass_somGetApplyStub
#define M_Stack_somGetClassData SOMClass_somGetClassData
#define M_Stack_somSetClassData SOMClass_somSetClassData
#define M_Stack_somGetClassMtab SOMClass_somGetClassMtab
#define M_Stack_somGetInstanceOffset SOMClass_somGetInstanceOffset
#define M_Stack_somGetInstancePartSize SOMClass_somGetInstancePartSize
#define M_Stack_somGetInstanceSize SOMClass_somGetInstanceSize
#define M_Stack_somGetInstanceToken SOMClass_somGetInstanceToken
#define M_Stack_somGetMemberToken SOMClass_somGetMemberToken
#define M_Stack_somGetMethodData SOMClass_somGetMethodData
#define M_Stack_somGetRdStub SOMClass_somGetRdStub
#define M_Stack_somGetMethodDescriptor SOMClass_somGetMethodDescriptor
#define M_Stack_somGetMethodIndex SOMClass_somGetMethodIndex
#define M_Stack_somGetMethodToken SOMClass_somGetMethodToken
#define M_Stack_somGetName SOMClass_somGetName
#define M_Stack_somGetNthMethodData SOMClass_somGetNthMethodData
#define M_Stack_somGetNthMethodInfo SOMClass_somGetNthMethodInfo
#define M_Stack_somGetNumMethods SOMClass_somGetNumMethods
#define M_Stack_somGetNumStaticMethods SOMClass_somGetNumStaticMethods
#define M_Stack_somGetParent SOMClass_somGetParent
#define M_Stack_somGetParents SOMClass_somGetParents
#define M_Stack_somGetVersionNumbers SOMClass_somGetVersionNumbers
#define M_Stack_somFindMethod SOMClass_somFindMethod
#define M_Stack_somFindMethodOk SOMClass_somFindMethodOk
#define M_Stack_somFindSMethod SOMClass_somFindSMethod
#define M_Stack_somFindSMethodOk SOMClass_somFindSMethodOk
#define M_Stack_somLookupMethod SOMClass_somLookupMethod
#define M_Stack_somCheckVersion SOMClass_somCheckVersion
#define M_Stack_somDescendedFrom SOMClass_somDescendedFrom
#define M_Stack_somSupportsMethod SOMClass_somSupportsMethod
#define M_Stack_somDefinedMethod SOMClass_somDefinedMethod
#define M_Stack_somOverrideMtab SOMClass_somOverrideMtab
#define M_Stack_somDefaultInit SOMObject_somDefaultInit
#define M_Stack_somDestruct SOMObject_somDestruct
#define M_Stack_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define M_Stack_somDefaultAssign SOMObject_somDefaultAssign
#define M_Stack_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define M_Stack_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define M_Stack_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define M_Stack_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define M_Stack_somDefaultVAssign SOMObject_somDefaultVAssign
#define M_Stack_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define M_Stack_somInit SOMObject_somInit
#define M_Stack_somFree SOMObject_somFree
#define M_Stack_somGetClass SOMObject_somGetClass
#define M_Stack_somGetClassName SOMObject_somGetClassName
#define M_Stack_somGetSize SOMObject_somGetSize
#define M_Stack_somIsA SOMObject_somIsA
#define M_Stack_somIsInstanceOf SOMObject_somIsInstanceOf
#define M_Stack_somRespondsTo SOMObject_somRespondsTo
#define M_Stack_somDispatch SOMObject_somDispatch
#define M_Stack_somClassDispatch SOMObject_somClassDispatch
#define M_Stack_somCastObj SOMObject_somCastObj
#define M_Stack_somResetObj SOMObject_somResetObj
#define M_Stack_somDispatchV SOMObject_somDispatchV
#define M_Stack_somDispatchL SOMObject_somDispatchL
#define M_Stack_somDispatchA SOMObject_somDispatchA
#define M_Stack_somDispatchD SOMObject_somDispatchD
#define M_Stack_somPrintSelf SOMObject_somPrintSelf
#define M_Stack_somDumpSelf SOMObject_somDumpSelf
#define M_Stack_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_M_Stack_h */
